FROM node:lts-alpine

RUN npm install -g @go-task/cli

WORKDIR /lib

COPY . .

RUN npm install

RUN task wisdom:build

WORKDIR /lib/app/wisdom
RUN npm link

WORKDIR /app

ENV DATA_DIR=/data
ENV DIST_DIR=/dist
ENV NO_PREVIEW=true

EXPOSE 3000
EXPOSE 3001

ENTRYPOINT [ "wisdom", "serve" ]