version: "3"

dotenv: [".env"]

tasks:
  bakery:build:
    deps: [safe-type:build, wholemeal:build]
    dir: "{{.TASKFILE_DIR}}/lib/bakery"
    cmds:
      - rm -rf dist
      - npx webpack
    env:
      PRODUCTION: "true"

  esbuild-workers:build:
    dir: "{{.TASKFILE_DIR}}/lib/esbuild-workers"
    cmds:
      - npx tsc

  url:build:
    dir: "{{.TASKFILE_DIR}}/lib/url"
    cmds:
      - npx tsc

  wisdom:build:
    deps:
      - puristee:build
      - safe-type:build
      - moulding-tin:build
      - bakery:build
      - esbuild-workers:build
      - url:build
    dir: "{{.TASKFILE_DIR}}/app/wisdom"
    cmds:
      - node ./build.js

  pauphie-blog:serve:
    dir: "{{.TASKFILE_DIR}}/app/pauphie-blog"
    cmds:
      - npm run serve

  pauphie-blog:setup:
    dir: "{{.TASKFILE_DIR}}/app/pauphie-blog"
    cmds:
      - npm run setup

  wisdom:dev:
    dir: "{{.TASKFILE_DIR}}/app/wisdom"
    cmds:
      - node ./build.js
      - task: pauphie-blog:serve

  bakery:dev:
    deps: [safe-type:build, wholemeal:build]
    dir: "{{.TASKFILE_DIR}}/lib/bakery"
    cmds:
      - npx webpack

  fs-db:build:
    deps: [moulding-tin:build, safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/fs-db"
    cmds:
      - npm run build

  moulding-tin:build:
    dir: "{{.TASKFILE_DIR}}/lib/moulding-tin"
    cmds:
      - npm run build

  puristee:build:
    deps: [fs-db:build, safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/puristee"
    cmds:
      - rm -rf dist
      - npm run build

  safe-type:build:
    dir: "{{.TASKFILE_DIR}}/lib/safe-type"
    cmds:
      - npm run build

  set:build:
    dir: "{{.TASKFILE_DIR}}/lib/set"
    cmds:
      - npm run build

  wholemeal:build:
    deps: [safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/wholemeal"
    cmds:
      - npx tsc

  wholemeal:test:
    dir: "{{.TASKFILE_DIR}}/lib/wholemeal"
    cmds:
      - node --test --import tsx ./src/**/*.test.ts
