version: "3"

dotenv: [".env"]

tasks:
  bakery:build:
    deps: [safe-type:build, wholemeal:build]
    dir: "{{.TASKFILE_DIR}}/lib/bakery"
    cmds:
      - npm run build
  bakery:dev:
    deps: [safe-type:build, wholemeal:build]
    dir: "{{.TASKFILE_DIR}}/lib/bakery"
    cmds:
      - npm run dev

  fs-db:build:
    deps: [moulding-tin:build, safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/fs-db"
    cmds:
      - npm run build

  moulding-tin:build:
    dir: "{{.TASKFILE_DIR}}/lib/moulding-tin"
    cmds:
      - npm run build

  puristee:build:
    deps: [fs-db:build, safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/puristee"
    cmds:
      - rm -rf dist
      - npm run build

  safe-type:build:
    dir: "{{.TASKFILE_DIR}}/lib/safe-type"
    cmds:
      - npm run build

  wholemeal:build:
    deps: [safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/wholemeal"
    cmds:
      - npm run build

  wholemeal:test:
    deps: [safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/wholemeal"
    cmds:
      - npm run test

  effuse:setup:
    cmds:
      - openssl req -new -newkey rsa:4096 -nodes -keyout signing_key.key -out public_key.csr -subj "/C=UK/CN=local"
      - openssl x509 -req -sha512 -days 365 -in public_key.csr -signkey signing_key.key -out private_key.pem
    dir: "{{.TASKFILE_DIR}}/app/effuse/data"

  effuse:build:
    deps: [puristee:build, safe-type:build, moulding-tin:build]
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - rm -rf dist
      - npx tsc
      - npx webpack
      
  effuse:run-ui:
    deps: [effuse:build]
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - npx webpack serve

  effuse:api-test:
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - rm -rf ./data/db
      - node --test --import tsx ./tests/**/*.test.ts
    env:
      SSO_BASE: http://localhost:3000/
      LOCAL_BASE: http://localhost:3002/
      UI_URL: http://localhost:3001/

  effuse:run-sso:
    deps: [effuse:build]
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - node ./dist/src/sso.js
    env:
      NODE_PATH: ./dist/src
      DATA_DIR: ./data
      UI_URL: http://localhost:3001/

  effuse:run-local:
    deps: [effuse:build]
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - node ./dist/src/local.js
    env:
      NODE_PATH: ./dist/src
      DATA_DIR: ./data
      SSO_URL: http://localhost:3000/
      UI_URL: http://localhost:3001/
