version: "3"

dotenv: [".env"]

tasks:
  bakery:build:
    deps: [safe-type:build, wholemeal:build]
    dir: "{{.TASKFILE_DIR}}/lib/bakery"
    cmds:
      - npm run build
  bakery:dev:
    deps: [safe-type:build, wholemeal:build]
    dir: "{{.TASKFILE_DIR}}/lib/bakery"
    cmds:
      - npm run dev

  fs-db:build:
    deps: [moulding-tin:build, safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/fs-db"
    cmds:
      - npm run build

  moulding-tin:build:
    dir: "{{.TASKFILE_DIR}}/lib/moulding-tin"
    cmds:
      - npm run build

  puristee:build:
    deps: [fs-db:build, safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/puristee"
    cmds:
      - npm run build

  safe-type:build:
    dir: "{{.TASKFILE_DIR}}/lib/safe-type"
    cmds:
      - npm run build

  wholemeal:build:
    deps: [safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/wholemeal"
    cmds:
      - npm run build

  wholemeal:test:
    deps: [safe-type:build]
    dir: "{{.TASKFILE_DIR}}/lib/wholemeal"
    cmds:
      - npm run test

  effuse:build-sso:
    deps: [puristee:build, safe-type:build, moulding-tin:build]
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - rm -rf dist
      - npm run build

  effuse:api-test:
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - node --test --import tsx ./tests/**/*.test.ts

  effuse:run-sso:
    deps: [effuse:build-sso]
    dir: "{{.TASKFILE_DIR}}/app/effuse"
    cmds:
      - node ./dist/src/sso.js
    env:
      NODE_PATH: ./dist/src
