version: "3.9"
services:
  wisdom:
    env_file:
      - .env
    build:
      context: ../../
      dockerfile: Dockerfile
      target: wisdom
    restart: unless-stopped
    volumes:
      - .:/app:r
      - data:/data:rw
      - dist:/dist:rw

  preview:
    image: lipanski/docker-static-website:latest
    restart: unless-stopped
    volumes:
      - dist:/home/static:r
    environment:
      VIRTUAL_HOST: preview.paulandsophie.uk
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: preview.paulandsophie.uk

volumes:
  data:
  dist:
